### ISSUE TITLE
questions about the NSD dataset

### ISSUE THREAD

**Issue by xiaominli1020** [littlepure2333/MindBridge#2]
First of all, thank you for your wonderful project and congrats your acceptance!

I have some questions about the NSD dataset.

1. I cannot find these two files as follows, could you please tell me where can I download them?

![image](https://github.com/littlepure2333/MindBridge/assets/25433111/6c437c85-ad80-41bd-b189-039ad9031a13)
![image](https://github.com/littlepure2333/MindBridge/assets/25433111/26159d36-7069-48ef-8e3f-deb7c4c9723c)

**Comment by littlepure2333** [comment]
Hi, thanks for your appreciation. 

Sorry for the inconvenience. These two files are annotations of the COCO dataset, which should be auto-downloaded by NSDAccess or can be manually downloaded from [http://images.cocodataset.org/annotations/annotations_trainval2017.zip](http://images.cocodataset.org/annotations/annotations_trainval2017.zip)

Hope this clarifies 😊
