### ISSUE TITLE
Question about finetuning implementation in your code.

### ISSUE THREAD

**Issue by zhibotian** [littlepure2333/MindBridge#3]
Hello,
Congratulations on having your work accepted by CVPR 2024! Your research is incredibly meaningful and fascinating.
I have a question regarding your code. In your paper, you mentioned using reset-tuning, which involves freezing the brain translator to retain the pretrained cross-subject knowledge. Could you provide guidance on how to implement this in the code?
Thank you, and I look forward to your response.

**Comment by littlepure2333** [comment]
Hi, thanks for your feedback. I missed it while reorganizing the code, but I have added it in the latest version. Please refer to: https://github.com/littlepure2333/MindBridge/blob/bc359f4eeef31e07d54298f26c9dc5eafbd307e3/src/main.py#L66
