### ISSUE TITLE
Questions about the size of the dataset

### ISSUE THREAD

**Issue by percy4** [littlepure2333/MindBridge#5]
When I looked at the NSD dataset, the file was very large, 87TB in size, which was too large for my device. Is this the size of the dataset that you actually use? What is the size of your data?

**Comment by littlepure2333** [comment]
Hi, actually you don't need to download the entire NSD dataset. We are using the preprocessed data described [here](https://github.com/littlepure2333/MindBridge?tab=readme-ov-file#data), which should not exceed 200GB in size.
