### ISSUE TITLE
Question about claiming "one single model"

### ISSUE THREAD

**Issue by Nickyang4900** [littlepure2333/MindBridge#7]
Hi, it is a good paper.

Brain Embedder and Brain Builder are subject-wise, so there should be multiple of them when testing. But section 4.1 states "for multiple subjects using one single model". I think this is contradictory, or am I misunderstanding something?

Thank you!

**Comment by littlepure2333** [comment]
Hi, thanks for your interest in our work. Since we train multiple subjects simultaneously and result in one model consisting of multiple brain builders, it is indeed a single model. Let me know if you have any further questions :)
