### ISSUE TITLE
A question about VD

### ISSUE THREAD

**Issue by zhibotian** [littlepure2333/MindBridge#8]
Hello, in MindBridge, the output length of image and text embeddings is 768, which is then fed into VD. However, some works use embeddings with a length of 1024. Should the embedding length for VD also be adjusted to 1024, or are additional modifications needed? Thanks.

**Comment by littlepure2333** [comment]
Hi, thanks for your question. As far as I know, VD only supports embeddings with a length of 768. You might consider switching to other generative models as an alternative to VD.

**Comment by zhibotian** [comment]
Thanks for your reply.
